Load Dataset

In [1]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Summer Internship/Week-2/student-por.csv')

Dataset Information

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   school      649 non-null    object
 1   sex         649 non-null    object
 2   age         649 non-null    int64 
 3   address     649 non-null    object
 4   famsize     649 non-null    object
 5   Pstatus     649 non-null    object
 6   Medu        649 non-null    int64 
 7   Fedu        649 non-null    int64 
 8   Mjob        649 non-null    object
 9   Fjob        649 non-null    object
 10  reason      649 non-null    object
 11  guardian    649 non-null    object
 12  traveltime  649 non-null    int64 
 13  studytime   649 non-null    int64 
 14  failures    649 non-null    int64 
 15  schoolsup   649 non-null    object
 16  famsup      649 non-null    object
 17  paid        649 non-null    object
 18  activities  649 non-null    object
 19  nursery     649 non-null    object
 20  higher    

Data Types

In [ ]:
df.dtypes


,0
school,object
sex,object
age,int64
address,object
famsize,object
Pstatus,object
Medu,int64
Fedu,int64
Mjob,object
Fjob,object


 Statistical Summary(Numerical Columns)

In [ ]:
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000
mean,16.744222,2.514638,2.306626,1.568567,1.930663,0.221880,3.930663,3.180277,3.184900,1.502311,2.280431,3.536210,3.659476,11.399076,11.570108,11.906009
std,1.218138,1.134552,1.099931,0.748660,0.829510,0.593235,0.955717,1.051093,1.175766,0.924834,1.284380,1.446259,4.640759,2.745265,2.913639,3.230656
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,16.000000,2.000000,1.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,2.000000,0.000000,10.000000,10.000000,10.000000
50%,17.000000,2.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,2.000000,11.000000,11.000000,12.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,6.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,32.000000,19.000000,19.000000,19.000000


Statistical Summary(All Columns)

In [ ]:
df.describe(include='all')


,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,649,649,649.000000,649,649,649,649.000000,649.000000,649,649,...,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000
unique,2,2,NaN,2,2,2,NaN,NaN,5,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,GP,F,NaN,U,GT3,T,NaN,NaN,other,other,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,423,383,NaN,452,457,569,NaN,NaN,258,367,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,16.744222,NaN,NaN,NaN,2.514638,2.306626,NaN,NaN,...,3.930663,3.180277,3.184900,1.502311,2.280431,3.536210,3.659476,11.399076,11.570108,11.906009
std,NaN,NaN,1.218138,NaN,NaN,NaN,1.134552,1.099931,NaN,NaN,...,0.955717,1.051093,1.175766,0.924834,1.284380,1.446259,4.640759,2.745265,2.913639,3.230656
min,NaN,NaN,15.000000,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,16.000000,NaN,NaN,NaN,2.000000,1.000000,NaN,NaN,...,4.000000,3.000000,2.000000,1.000000,1.000000,2.000000,0.000000,10.000000,10.000000,10.000000
50%,NaN,NaN,17.000000,NaN,NaN,NaN,2.000000,2.000000,NaN,NaN,...,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,2.000000,11.000000,11.000000,12.000000
75%,NaN,NaN,18.000000,NaN,NaN,NaN,4.000000,3.000000,NaN,NaN,...,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,6.000000,13.000000,13.000000,14.000000


Unique Value Counts

In [ ]:
for col in df.columns:
 print(f'\n{col}')
 print('Unique Values:', df[col].nunique())


school
Unique Values: 2

sex
Unique Values: 2

age
Unique Values: 8

address
Unique Values: 2

famsize
Unique Values: 2

Pstatus
Unique Values: 2

Medu
Unique Values: 5

Fedu
Unique Values: 5

Mjob
Unique Values: 5

Fjob
Unique Values: 5

reason
Unique Values: 4

guardian
Unique Values: 3

traveltime
Unique Values: 4

studytime
Unique Values: 4

failures
Unique Values: 4

schoolsup
Unique Values: 2

famsup
Unique Values: 2

paid
Unique Values: 2

activities
Unique Values: 2

nursery
Unique Values: 2

higher
Unique Values: 2

internet
Unique Values: 2

romantic
Unique Values: 2

famrel
Unique Values: 5

freetime
Unique Values: 5

goout
Unique Values: 5

Dalc
Unique Values: 5

Walc
Unique Values: 5

health
Unique Values: 5

absences
Unique Values: 24

G1
Unique Values: 17

G2
Unique Values: 16

G3
Unique Values: 17


 Sample Values

In [ ]:
for col in df.columns:
 print('\n', col)
 print(df[col].unique()[:10])


 school
['GP' 'MS']

 sex
['F' 'M']

 age
[18 17 15 16 19 22 20 21]

 address
['U' 'R']

 famsize
['GT3' 'LE3']

 Pstatus
['A' 'T']

 Medu
[4 1 3 2 0]

 Fedu
[4 1 2 3 0]

 Mjob
['at_home' 'health' 'other' 'services' 'teacher']

 Fjob
['teacher' 'other' 'services' 'health' 'at_home']

 reason
['course' 'other' 'home' 'reputation']

 guardian
['mother' 'father' 'other']

 traveltime
[2 1 3 4]

 studytime
[2 3 1 4]

 failures
[0 3 1 2]

 schoolsup
['yes' 'no']

 famsup
['no' 'yes']

 paid
['no' 'yes']

 activities
['no' 'yes']

 nursery
['yes' 'no']

 higher
['yes' 'no']

 internet
['no' 'yes']

 romantic
['no' 'yes']

 famrel
[4 5 3 1 2]

 freetime
[3 2 4 1 5]

 goout
[4 3 2 1 5]

 Dalc
[1 2 5 3 4]

 Walc
[1 3 2 4 5]

 health
[3 5 1 2 4]

 absences
[ 4  2  6  0 10  8 16 14  1 12]

 G1
[ 0  9 12 14 11 13 10 15 17  8]

 G2
[11 13 14 12 16 17  8 10 15  9]

 G3
[11 12 14 13 17 15  7 10 16  9]


Feature Summary Table

In [ ]:
summary = pd.DataFrame({
 'Column': df.columns,
 'DataType': df.dtypes.values,
 'MissingValues': df.isnull().sum().values,
 'UniqueValues': df.nunique().values
})
summary

,Column,DataType,MissingValues,UniqueValues
0,school,object,0,2
1,sex,object,0,2
2,age,int64,0,8
3,address,object,0,2
4,famsize,object,0,2
5,Pstatus,object,0,2
6,Medu,int64,0,5
7,Fedu,int64,0,5
8,Mjob,object,0,5
9,Fjob,object,0,5


Identify Feature Types


In [ ]:
import pandas as pd
import numpy as np

numeric_cols = df.select_dtypes(include=np.number).columns

categorical_cols = df.select_dtypes(
    include=['object', 'category']
).columns

print('Numerical Features')
print(list(numeric_cols))

print('\nCategorical Features')
print(list(categorical_cols))

Numerical Features
['age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']

Categorical Features
['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob', 'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic']
